//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonWayFormProjet.LemonServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lemonway.fr/", ConfigurationName="LemonServices.LemonWayMetiersSoap")]
    public interface LemonWayMetiersSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément FibonacciResult de l'espace de noms http://lemonway.fr/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lemonway.fr/Fibonacci", ReplyAction="*")]
        LemonWayFormProjet.LemonServices.FibonacciResponse Fibonacci(LemonWayFormProjet.LemonServices.FibonacciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lemonway.fr/Fibonacci", ReplyAction="*")]
        System.Threading.Tasks.Task<LemonWayFormProjet.LemonServices.FibonacciResponse> FibonacciAsync(LemonWayFormProjet.LemonServices.FibonacciRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément xml de l'espace de noms http://lemonway.fr/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lemonway.fr/XmlToJson", ReplyAction="*")]
        LemonWayFormProjet.LemonServices.XmlToJsonResponse XmlToJson(LemonWayFormProjet.LemonServices.XmlToJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lemonway.fr/XmlToJson", ReplyAction="*")]
        System.Threading.Tasks.Task<LemonWayFormProjet.LemonServices.XmlToJsonResponse> XmlToJsonAsync(LemonWayFormProjet.LemonServices.XmlToJsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibonacciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fibonacci", Namespace="http://lemonway.fr/", Order=0)]
        public LemonWayFormProjet.LemonServices.FibonacciRequestBody Body;
        
        public FibonacciRequest() {
        }
        
        public FibonacciRequest(LemonWayFormProjet.LemonServices.FibonacciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lemonway.fr/")]
    public partial class FibonacciRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int n;
        
        public FibonacciRequestBody() {
        }
        
        public FibonacciRequestBody(int n) {
            this.n = n;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibonacciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FibonacciResponse", Namespace="http://lemonway.fr/", Order=0)]
        public LemonWayFormProjet.LemonServices.FibonacciResponseBody Body;
        
        public FibonacciResponse() {
        }
        
        public FibonacciResponse(LemonWayFormProjet.LemonServices.FibonacciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lemonway.fr/")]
    public partial class FibonacciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FibonacciResult;
        
        public FibonacciResponseBody() {
        }
        
        public FibonacciResponseBody(string FibonacciResult) {
            this.FibonacciResult = FibonacciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJson", Namespace="http://lemonway.fr/", Order=0)]
        public LemonWayFormProjet.LemonServices.XmlToJsonRequestBody Body;
        
        public XmlToJsonRequest() {
        }
        
        public XmlToJsonRequest(LemonWayFormProjet.LemonServices.XmlToJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lemonway.fr/")]
    public partial class XmlToJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public XmlToJsonRequestBody() {
        }
        
        public XmlToJsonRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonResponse", Namespace="http://lemonway.fr/", Order=0)]
        public LemonWayFormProjet.LemonServices.XmlToJsonResponseBody Body;
        
        public XmlToJsonResponse() {
        }
        
        public XmlToJsonResponse(LemonWayFormProjet.LemonServices.XmlToJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lemonway.fr/")]
    public partial class XmlToJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlToJsonResult;
        
        public XmlToJsonResponseBody() {
        }
        
        public XmlToJsonResponseBody(string XmlToJsonResult) {
            this.XmlToJsonResult = XmlToJsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LemonWayMetiersSoapChannel : LemonWayFormProjet.LemonServices.LemonWayMetiersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LemonWayMetiersSoapClient : System.ServiceModel.ClientBase<LemonWayFormProjet.LemonServices.LemonWayMetiersSoap>, LemonWayFormProjet.LemonServices.LemonWayMetiersSoap {
        
        public LemonWayMetiersSoapClient() {
        }
        
        public LemonWayMetiersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LemonWayMetiersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LemonWayMetiersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LemonWayMetiersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LemonWayFormProjet.LemonServices.FibonacciResponse LemonWayFormProjet.LemonServices.LemonWayMetiersSoap.Fibonacci(LemonWayFormProjet.LemonServices.FibonacciRequest request) {
            return base.Channel.Fibonacci(request);
        }
        
        public string Fibonacci(int n) {
            LemonWayFormProjet.LemonServices.FibonacciRequest inValue = new LemonWayFormProjet.LemonServices.FibonacciRequest();
            inValue.Body = new LemonWayFormProjet.LemonServices.FibonacciRequestBody();
            inValue.Body.n = n;
            LemonWayFormProjet.LemonServices.FibonacciResponse retVal = ((LemonWayFormProjet.LemonServices.LemonWayMetiersSoap)(this)).Fibonacci(inValue);
            return retVal.Body.FibonacciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LemonWayFormProjet.LemonServices.FibonacciResponse> LemonWayFormProjet.LemonServices.LemonWayMetiersSoap.FibonacciAsync(LemonWayFormProjet.LemonServices.FibonacciRequest request) {
            return base.Channel.FibonacciAsync(request);
        }
        
        public System.Threading.Tasks.Task<LemonWayFormProjet.LemonServices.FibonacciResponse> FibonacciAsync(int n) {
            LemonWayFormProjet.LemonServices.FibonacciRequest inValue = new LemonWayFormProjet.LemonServices.FibonacciRequest();
            inValue.Body = new LemonWayFormProjet.LemonServices.FibonacciRequestBody();
            inValue.Body.n = n;
            return ((LemonWayFormProjet.LemonServices.LemonWayMetiersSoap)(this)).FibonacciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LemonWayFormProjet.LemonServices.XmlToJsonResponse LemonWayFormProjet.LemonServices.LemonWayMetiersSoap.XmlToJson(LemonWayFormProjet.LemonServices.XmlToJsonRequest request) {
            return base.Channel.XmlToJson(request);
        }
        
        public string XmlToJson(string xml) {
            LemonWayFormProjet.LemonServices.XmlToJsonRequest inValue = new LemonWayFormProjet.LemonServices.XmlToJsonRequest();
            inValue.Body = new LemonWayFormProjet.LemonServices.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            LemonWayFormProjet.LemonServices.XmlToJsonResponse retVal = ((LemonWayFormProjet.LemonServices.LemonWayMetiersSoap)(this)).XmlToJson(inValue);
            return retVal.Body.XmlToJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LemonWayFormProjet.LemonServices.XmlToJsonResponse> LemonWayFormProjet.LemonServices.LemonWayMetiersSoap.XmlToJsonAsync(LemonWayFormProjet.LemonServices.XmlToJsonRequest request) {
            return base.Channel.XmlToJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<LemonWayFormProjet.LemonServices.XmlToJsonResponse> XmlToJsonAsync(string xml) {
            LemonWayFormProjet.LemonServices.XmlToJsonRequest inValue = new LemonWayFormProjet.LemonServices.XmlToJsonRequest();
            inValue.Body = new LemonWayFormProjet.LemonServices.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            return ((LemonWayFormProjet.LemonServices.LemonWayMetiersSoap)(this)).XmlToJsonAsync(inValue);
        }
    }
}
